name: Build,Analyze,scan

on:
  push:
    branches:
      - main


jobs:
  build-analyze-scan:
    name: Build
    runs-on: [self-hosted]
    steps:
      
      - name: Docker build and push
        run: |
          # Run commands to build and push Docker images
          docker build -t tic-tac-toe .
          docker tag tic-tac-toe rahulpatelabc/tic-tac-toe:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push rahulpatelabc/tic-tac-toe:latest
        env:
          DOCKER_CLI_ACI: 1    
  
  deploy:
    needs: build-analyze-scan
    runs-on: [self-hosted]
    steps:
      - name: Pull the Docker image
        run: docker pull rahulpatelabc/tic-tac-toe:latest
            
      - name: Run the container
        run: docker run -d --name ticgame -p 3000:3000 rahulpatelabc/tic-tac-toe:latest
